# Generated by Django 4.2.15 on 2024-08-08 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('preferences', models.TextField(blank=True)),
                ('past_interactions', models.ManyToManyField(blank=True, related_name='interacted_with', to=settings.AUTH_USER_MODEL)),
                ('skills_offered', models.ManyToManyField(related_name='offered_by', to='users.skill')),
                ('skills_sought', models.ManyToManyField(related_name='sought_by', to='users.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
